### ISSUE TITLE
Create Acceptance Criteria

### ISSUE THREAD

**Issue by kanggeon123** [samxbrown/Kino-Hunt#5]
# Acceptance Criteria
Given I am using the website to find the movie I want to watch
WHEN I open the website
Then list of movie genres is displayed in the website
When I choose the genre
Then list of random movies with chosen genre is displayed
When I choose the movie
Then IMDb link will be shown and list of actors in the movie is displayed
When I choose the actor
Then IMDB link for the actor is displayed
When I click the IMDB link
Then the website will be refreshed and show the main page.

**Comment by samxbrown** [comment]
complete
